name: Alerta Examenes Ocupacionales

on:
  schedule:
    - cron: '30 12 15,30 * *'
  workflow_dispatch:

jobs:
  ejecutar-alerta:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar robot SST
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python alertas_examenes.py
